// Export pages
export 'login/login_widget.dart' show LoginWidget;
export 'login2/login2_widget.dart' show Login2Widget;
export 'inicio/inicio_widget.dart' show InicioWidget;
export 'empleados/empleados_widget.dart' show EmpleadosWidget;
export 'acta_nacimiento/acta_nacimiento_widget.dart' show ActaNacimientoWidget;
export 'acta_matrimonio/acta_matrimonio_widget.dart' show ActaMatrimonioWidget;
export 'servicios/servicios_widget.dart' show ServiciosWidget;
export 'olvidee_contra/olvidee_contra_widget.dart' show OlvideeContraWidget;
export 'siguientepaso/siguientepaso_widget.dart' show SiguientepasoWidget;
export 'tercerpaso/tercerpaso_widget.dart' show TercerpasoWidget;
export 'olvidecurp/olvidecurp_widget.dart' show OlvidecurpWidget;
export 'curp2/curp2_widget.dart' show Curp2Widget;
export 'curp3/curp3_widget.dart' show Curp3Widget;
export 'cita/cita_widget.dart' show CitaWidget;
export 'servicios1/servicios1_widget.dart' show Servicios1Widget;
export 'servicios2/servicios2_widget.dart' show Servicios2Widget;
export 'cita_regis/cita_regis_widget.dart' show CitaRegisWidget;
export 'concluciones/concluciones_widget.dart' show ConclucionesWidget;
